### ISSUE TITLE
GraphViz autoLayout stacking one relationship on top of another in deploymentEnvironment

### ISSUE THREAD

**Issue by j0w0uby** [structurizr/graphviz#3]
### Description

GraphViz autoLayout is stacking one relationship on top of another

### Steps to reproduce

1. Create model in DSL
2. Create deploymentEnvironment and view

### Screenshot

![Screenshot 2023-05-09 195333](https://github.com/structurizr/cloud/assets/133048369/1c73e501-2cce-4d57-89b3-953b3535068f)

### Severity

Minor

### Priority

Low

### Resolution

I have no budget, please fix this for free

**Comment by simonbrowndotje** [comment]
See https://github.com/structurizr/structurizr/issues/169 ... I'd recommend switching to manual layout.
